name: CI Pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - uses: actions/checkout@v3

      # 2. 登录 Docker Hub（新增部分）
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 3. 后续步骤（原有内容）
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install pytest
      - run: python -m pytest tests/ -v
